image: Ubuntu
stack: node 12, jdk 8, python 2

environment:
  matrix:
    - DRIVER_REPO: "nodejs-driver"
    - DRIVER_REPO: "java-driver"
    - DRIVER_REPO: "csharp-driver"
    - DRIVER_REPO: "cpp-driver"

install:
- source ./install.sh

for:
  - matrix:
      only:
        - DRIVER_REPO: "nodejs-driver"
    test_script:
      # TODO: Use stable ${DRIVER_LATEST_TAG}
      - git checkout master
      - export TEST_TRACE=on
      - npm install
      - npm run server_api
  - matrix:
      only:
        - DRIVER_REPO: "java-driver"
    test_script:
      - git checkout ${DRIVER_LATEST_TAG}
      - mvn -B -V install -DskipTests
      - mvn -B -V verify --batch-mode --show-version -Dccm.version=${CCM_VERSION} -DskipSerialITs -DskipIsolatedITs -Dmaven.javadoc.skip=true
  - matrix:
      only:
        - DRIVER_REPO: "csharp-driver"
    test_script:
      # TODO: Use stable ${DRIVER_LATEST_TAG}
      - git checkout master
      - export DOTNET_CLI_TELEMETRY_OPTOUT=1
      - export CASSANDRA_VERSION=${CCM_VERSION}
      - export CCM_SSL_PATH=$CCM_PATH/ssl
      - dotnet --version
      - dotnet restore src
      - dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -f netcoreapp2.1 -c Release --filter TestCategory=serverapi --logger:Appveyor
  - matrix:
      only:
        - DRIVER_REPO: "cpp-driver"
    test_script:
      - git checkout ${DRIVER_LATEST_TAG}
      - export CI_INTEGRATION_ENABLED=true
      - export OS_VERSION=ubuntu/bionic
      - export OS_DISTRO=ubuntu
      - export SMOKE_TEST_FILTER=BasicsTests*:CassandraTypes/*
      - . .build.sh
      - build_driver 'CASS'
      - build/cassandra-integration-tests --category=cassandra --gtest_filter=${SMOKE_TEST_FILTER} --gtest_output=xml:integration-smoke-test-results.xml --version=${CCM_VERSION}
    on_finish:
      - find "${APPVEYOR_BUILD_FOLDER}" -type f -name 'integration-smoke-test-results.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/${APPVEYOR_JOB_ID}"

build: off
