image: Ubuntu
stack: node 12, jdk 8, python 2

environment:
  matrix:
    - DRIVER_REPO: "nodejs-driver"
      CASSANDRA_VERSION: $(CCM_VERSION)
    - DRIVER_REPO: "java-driver"
      CASSANDRA_VERSION: "%CCM_VERSION%"
    - DRIVER_REPO: "csharp-driver"
      CASSANDRA_VERSION: "%CCM_VERSION%"

install:
- source ./install.sh

for:
  - matrix:
      only:
        - DRIVER_REPO: "nodejs-driver"
    test_script:
      # TODO: Use stable $DRIVER_TAG
      - git checkout master
      - export TEST_TRACE=on
      - npm install
      - npm run server_api
  - matrix:
      only:
          - DRIVER_REPO: "java-driver"
    test_script:
      - git checkout $DRIVER_TAG
      - mvn -B -V install -DskipTests
      - mvn -B -V verify --batch-mode --show-version -Dccm.version=$CCM_VERSION -DskipSerialITs -DskipIsolatedITs -Dmaven.javadoc.skip=true
  - matrix:
      only:
        - DRIVER_REPO: "csharp-driver"
    test_script:
      # TODO: Use stable $DRIVER_TAG
      - git checkout master
      - export DOTNET_CLI_TELEMETRY_OPTOUT=1
      - export CASSANDRA_VERSION=$CCM_VERSION
      - export CCM_SSL_PATH=$CCM_PATH/ssl
      - dotnet --version
      - dotnet restore src
      - dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -f netcoreapp2.1 -c Release --filter TestCategory=serverapi --logger:Appveyor

build: off
