image: Ubuntu
stack: node 12, jdk 8, python 2

environment:
  matrix:
    - DRIVER_REPO: "nodejs-driver"
    - DRIVER_REPO: "java-driver"
    - DRIVER_REPO: "csharp-driver"

install:
- source ./install.sh

for:
  - matrix:
      only:
        - DRIVER_REPO: "nodejs-driver"
    test_script:
      - export TEST_TRACE=on
      # TODO: Use stable $DRIVER_TAG
      - git checkout master
      - npm install
      - npm run server_api
  - matrix:
      only:
          - DRIVER_REPO: "java-driver"
    test_script:
      - git checkout $DRIVER_TAG
      - mvn -B -V install -DskipTests
      - mvn -B -V verify --batch-mode --show-version -Dccm.version=$CCM_VERSION -DskipSerialITs -DskipIsolatedITs -Dmaven.javadoc.skip=true
  - matrix:
      only:
        - DRIVER_REPO: "csharp-driver"
    test_script:
      - dotnet --version
      - git checkout $DRIVER_TAG

build: off