stack: node 12, jdk 8, python 2

version: '{build}'

environment:
  global:
    CCM_SHA_VERSION: 97e3736d4c29bd86878d2b3372f757d18fc89520
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      DRIVER_REPO: csharp-driver
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      DRIVER_REPO: csharp-driver
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      DRIVER_REPO: java-driver
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      DRIVER_REPO: nodejs-driver
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      DRIVER_REPO: cpp-driver

install:
- source ./install.sh

for:
  - matrix:
      only:
        - DRIVER_REPO: "nodejs-driver"
    test_script:
      - npm install mocha-appveyor-reporter@0
      - git checkout ${DRIVER_LATEST_TAG}
      - export TEST_TRACE=on
      - export multi="spec=- mocha-appveyor-reporter=-"
      - npm install
      - ./node_modules/.bin/mocha test/integration/short -g '@SERVER_API' --recursive -R mocha-appveyor-reporter --exit
  - matrix:
      only:
        - DRIVER_REPO: "java-driver"
    test_script:
      # - git checkout ${DRIVER_LATEST_TAG} # Use 4.x until the next release
      - git checkout 4.x
      - mvn -B -V install -DskipTests
      - mvn -B -V verify --batch-mode --show-version -Dccm.version=${CCM_VERSION} -DskipSerialITs -DskipIsolatedITs -Dmaven.javadoc.skip=true -Dmaven.test.failure.ignore=false
    on_finish:
      - find "${APPVEYOR_BUILD_FOLDER}" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/${APPVEYOR_JOB_ID}"
  - matrix:
      only:
        - DRIVER_REPO: "csharp-driver"
          APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    test_script:
      #- git checkout ${DRIVER_LATEST_TAG} ## 3.15.0 tests have an issue with latest ccm
      - git checkout master
      - export DOTNET_CLI_TELEMETRY_OPTOUT=1
      - export CASSANDRA_VERSION=${CCM_VERSION}
      - export CCM_SSL_PATH=$CCM_PATH/ssl
      - dotnet --version
      - dotnet restore src
      - dotnet test src/Cassandra.IntegrationTests/Cassandra.IntegrationTests.csproj -f netcoreapp3.1 -c Release --filter TestCategory=serverapi --logger:Appveyor
  - matrix:
      only:
        - DRIVER_REPO: "csharp-driver"
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    init:
      - ps: Update-AppveyorBuild -Version "$($env:CCM_VERSION)#$($env:appveyor_build_number)" -Message "Apache Cassandra version $($env:CCM_VERSION)`r`nTest run for Apache Cassandra version $($env:CCM_VERSION) using the package at $($env:SERVER_PACKAGE_URL)."
    install:
      - ps: .\install_windows.ps1
    test_script:
    - ps: |
        //git checkout $env:DRIVER_LATEST_TAG // 3.15.0 tests have an issue with latest ccm
        git checkout master

        $env:CASSANDRA_VERSION=$env:CCM_VERSION
        $env:CCM_SSL_PATH="$env:CCM_PATH\ssl"
        $env:DOTNET_CLI_TELEMETRY_OPTOUT=1

        dotnet --info
        dotnet restore src
        dotnet build src\Cassandra.sln -c Release

        dotnet test src\Cassandra.IntegrationTests\Cassandra.IntegrationTests.csproj -c Release -f net462 --filter "(TestCategory=serverapi)" --logger:Appveyor
  - matrix:
      only:
        - DRIVER_REPO: "cpp-driver"
    test_script:
      - git checkout ${DRIVER_LATEST_TAG}
      - export CI_INTEGRATION_ENABLED=true
      - export OS_VERSION=ubuntu/bionic
      - export OS_DISTRO=ubuntu
      - export SMOKE_TEST_FILTER=BasicsTests*:CassandraTypes/*
      - . .build.sh
      - build_driver 'CASS'
      - build/cassandra-integration-tests --category=cassandra --gtest_filter=${SMOKE_TEST_FILTER} --gtest_output=xml:integration-smoke-test-results.xml --version=${CCM_VERSION}
    on_finish:
      - find "${APPVEYOR_BUILD_FOLDER}" -type f -name 'integration-smoke-test-results.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/${APPVEYOR_JOB_ID}"

build: off
