image: Ubuntu
stack: node 12, jdk 8, python 2

environment:
  matrix:
    - DRIVER_REPO: "nodejs-driver"
    - DRIVER_REPO: "java-driver"

install:
- sh: ./install.sh
- git clone --branch master --single-branch git@github.com:riptano/ccm.git
- pushd ccm || exit
- sudo python setup.py install
- popd
- ccm status || true
- export CCM_PATH="$(pwd)/ccm"
- export INSTALL_DIR="${HOME}/.ccm/repository/${CCM_VERSION}"
- echo $INSTALL_DIR
- mkdir -p $INSTALL_DIR
- wget $SERVER_PACKAGE_URL -O server.tar.gz
- ls
- pwd
- ls ${INSTALL_DIR}
- tar xzf server.tar.gz -C ${INSTALL_DIR} --strip-components=1 || exit
- sh: |
    # Add 0.version.txt file for ccm
    VERSION_TOKENS=($(echo ${CCM_VERSION} | sed -e "s/[\\.|-]/ /g"))
    echo "${VERSION_TOKENS[0]}.${VERSION_TOKENS[1]}.${VERSION_TOKENS[2]}" > "${INSTALL_DIR}/0.version.txt"
- ccm create test -v $CCM_VERSION
- ccm remove test
- git clone https://github.com/datastax/$DRIVER_REPO
- cd $DRIVER_REPO || exit
- git fetch --tags
- export DRIVER_TAG=$(git tag | grep -P '^v?\d+\.\d+\.\d+$' | tail -1)

for:
  - matrix:
      only:
        - DRIVER_REPO: "nodejs-driver"
    test_script:
      - export TEST_TRACE=on
      - git checkout NODEJS-599
      # TODO: Use stable $DRIVER_TAG
      #- git checkout $DRIVER_TAG
      - npm install
      - npm run server_api
  - matrix:
      only:
          - DRIVER_REPO: "java-driver"
    test_script:
      - echo "Hello from java"

build: off