image: Ubuntu
stack: node 12, jdk 8, python 2

environment:
  CCM_VERSION: 3.11.6
  SERVER_PACKAGE_URL: "http://archive.apache.org/dist/cassandra/3.11.6/apache-cassandra-3.11.6-bin.tar.gz"
  INSTALL_DIR: "${HOME}/.ccm/repository/${CCM_VERSION}"
  matrix:
    - DRIVER_REPO: "nodejs-driver"
    - DRIVER_REPO: "java-driver"

install:
- git clone --branch master --single-branch git@github.com:riptano/ccm.git
- pushd ccm || exit
- sudo python setup.py install
- popd
- ccm status || true
- sh: |
    # Download the C* binaries
    mkdir $INSTALL_DIR
    wget $SERVER_PACKAGE_URL -O server.tar.gz
    tar xzf server.tar.gz -C ${INSTALL_DIR} --strip-components=1
    VERSION_TOKENS=($(echo ${CCM_VERSION} | sed -e "s/[\\.|-]/ /g"))
    echo "${VERSION_TOKENS[0]}.${VERSION_TOKENS[1]}.${VERSION_TOKENS[2]}" > "${INSTALL_DIR}/0.version.txt"
    ccm create test -v $CCM_VERSION
    ccm remove test

for:
  -
    matrix:
      only:
        - DRIVER_REPO: "nodejs-driver"
    test_script:
      - echo "for nodejs $SERVER_PACKAGE_URL"
  -
    matrix:
      only:
          - DRIVER_REPO: "java-driver"
    test_script:
      - echo "for java $SERVER_PACKAGE_URL"

build: off